language: objective-c
osx_image: xcode9.2
rvm:
- 2.2
before_install:
- chmod a+x ./travisScripts/install.sh
- chmod a+x ./travisScripts/build.sh
install:
- ./travisScripts/install.sh
script:
- travis_wait 70 ./travisScripts/build.sh
