// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_dog = "CgkIway7ibscEAIQAw"; // <GPGSID>
        public const string achievement_send_love = "CgkIway7ibscEAIQDA"; // <GPGSID>
        public const string achievement_hugs_and_kisses = "CgkIway7ibscEAIQCg"; // <GPGSID>
        public const string achievement_repeater = "CgkIway7ibscEAIQBQ"; // <GPGSID>
        public const string achievement_senior = "CgkIway7ibscEAIQBA"; // <GPGSID>
        public const string achievement_junior = "CgkIway7ibscEAIQAg"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIway7ibscEAIQDw"; // <GPGSID>
        public const string achievement_keep_hitting = "CgkIway7ibscEAIQDg"; // <GPGSID>
        public const string achievement_hit_replay = "CgkIway7ibscEAIQDQ"; // <GPGSID>
        public const string achievement_santa = "CgkIway7ibscEAIQBg"; // <GPGSID>
        public const string achievement_lover = "CgkIway7ibscEAIQCQ"; // <GPGSID>
        public const string achievement_polyglot = "CgkIway7ibscEAIQCA"; // <GPGSID>
        public const string achievement_struggling = "CgkIway7ibscEAIQBw"; // <GPGSID>
        public const string achievement_puppy = "CgkIway7ibscEAIQAQ"; // <GPGSID>
        public const string achievement_sharing_is_caring = "CgkIway7ibscEAIQCw"; // <GPGSID>

}

